### PR TITLE
Setable Provider and History and a page for mov-cli

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Poseidon444** [comment]
This looks interesting, I'll take a look into it

**Comment by ghost** [comment]
Does everything work?

**Comment by Poseidon444** [comment]
Haven't tested everything yet, just read through it

**Comment by ghost** [comment]
Page: https://r3tr0ananas.github.io/mov-cli/

**Comment by ghost** [comment]
You can Search for Trending Movies and trending TVShows only for Theflix

**Pull request closed without merging**
