### PR TITLE
Feat/yt dlp downloading

### PR DESCRIPTION
**Pull request by THEGOLDENPRO**

### CODE REVIEW

**Comment by THEGOLDENPRO** [comment]
@r3tr0ananas We need to add this to the wiki.

**Comment by THEGOLDENPRO** [comment]
After this the feature freeze will be in place. I would like to keep changes in v4.3 to a minimal as I perform large refactors in v4.4

**Comment by ananasmoe** [comment]
@THEGOLDENPRO why don't we just merge this in to v4.4?

**Comment by THEGOLDENPRO** [comment]
> @THEGOLDENPRO why don't we just merge this in to v4.4?

Alright, I'll merge it with v4.4

**Pull request merged**
