### PR TITLE
Displaying release year for the movies

### PR DESCRIPTION
**Pull request by ShiNoNeko47**
Solves #20

### CODE REVIEW

**Comment by Poseidon444** [comment]
I'll take a look

**Comment by ShiNoNeko47** [comment]
Now it works with "olgply" site in python version too

**Comment by ShiNoNeko47** [comment]
Btw, why are there two different versions of the project in one repo?

**Comment by Poseidon444** [comment]
One is the python version, which supports a lot more providers and one is the posix-shell version which unfortunately supports only one provider

**Comment by ShiNoNeko47** [comment]
I'm done changing the python version if you want to check it out.

**Comment by Poseidon444** [comment]
I'll look into it

**Pull request merged**
