### PR TITLE
FIX: mov-cli current version doesnt work

### PR DESCRIPTION
**Pull request by ghost**
I Forgot that i moved __version__.py file and so currently mov-cli doesnt work

### CODE REVIEW

**Comment by ghost** [comment]
By the way maybe you forgot but check #26

**Review by Poseidon444 — APPROVED** [review]

**Comment by Poseidon444** [comment]
I haven't forgotten about that..

**Comment by Poseidon444** [comment]
I reverted the commits to a state where they worked, we will have to fix this issue and then we can commit. Is that okay?

**Comment by ghost** [comment]
So what is currently broken?

**Comment by Poseidon444** [comment]
it doesn't install

**Comment by ghost** [comment]
Does mov-cli doesnt install in general or the update?

**Comment by ghost** [comment]
By the way if you want you can add me on discord and we can talk about in dms and on discord its easier to reach to me because i only check github when getting a mail and i dont check mails alot so here: Ananas#1149

**Comment by Poseidon444** [comment]
Sure, I'd also recommend you join the ani-cli server since you can also find other contributors there

**Comment by ghost** [comment]
How about a Discord Server for mov-cli and what is now broken the update function or that mov-cli doesn´t install?

**Comment by Poseidon444** [comment]
Well, mov-cli doesn't install at all, I think it's probably the placement of __version__.py

**Comment by ghost** [comment]
so my version of mov-cli does install and work but the check function just says there is a update everytime but nothing more

**Comment by Poseidon444** [comment]
Rip

**Comment by ghost** [comment]
?

**Pull request merged**
