### PR TITLE
Beginning of some possible edits to the readme, see comment

### PR DESCRIPTION
**Pull request by wrenfannin**
If it would be useful I would be able to rewrite the readme or at least parts of it to make it looks a bit more fancy, I can include things like a showcase and detailed installation instructions for those who need them

### CODE REVIEW

**Comment by Poseidon444** [comment]
You can add the showcase and make it look fancy, i'll merge it once you do so. Thank you

**Comment by wrenfannin** [comment]
@Poseidon444 Do you like this sort of showcase for the code? I can do this for installation as well tomorrow if you like

**Comment by Poseidon444** [comment]
It looks good 👍

**Comment by Poseidon444** [comment]
Shall i merge it or do you want to make some more modifications?

**Comment by wrenfannin** [comment]
@Poseidon444 go ahead and merge for now, I will do more this weekend when work calms down a bit

cheers

**Review by Poseidon444 — COMMENTED** [review]
Ok sure

**Review by Poseidon444 — COMMENTED** [review]
It looks good

**Review by Poseidon444 — COMMENTED** [review]
I'll be merging it

**Review by Poseidon444 — APPROVED** [review]
Merged

**Pull request merged**
