### PR TITLE
Android support

### LINKED ISSUE #66: Android support?
I remember trying mov-cli on my phone a long time ago but it never worked so I assumed there wasn't support.

So is there currently android support for mov-cli?

### PR DESCRIPTION
**Pull request by THEGOLDENPRO**
- Added support for android because there wasn't any.
- Moved player code into its own class.
- Fixed startup.py exception on android.
- Fixes #66

### CODE REVIEW

**Comment by ghost** [comment]
Did you test your Version on PC and Android?

**Comment by THEGOLDENPRO** [comment]
> Did you test your Version on PC and Android?
> 

Yes I've tested, everything seems to work.

It would be nice if someone else with an android could also test it.

**Comment by ghost** [comment]
> > Did you test your Version on PC and Android?
> 
> Yes I've tested, everything seems to work.
> 
> It would be nice if someone else with an android could also test it.

@Poseidon444 can you try it?

**Comment by Poseidon444** [comment]
yes,i'll try testing it today

**Comment by Poseidon444** [comment]
i get an, lxml unable to compile error and i'm unable to install python 3.10 on termux. How do i install python 3.10 on termux?

**Comment by THEGOLDENPRO** [comment]
> i get an, lxml unable to compile error and i'm unable to install python 3.10 on termux. How do i install python 3.10 on termux?

No idea, my termux was running python 3.10 and everything worked fine. From what I've seen a lot of libraries are breaking on python 3.11.

Does mov-cli even work on 3.11? I think I've seen GitHub issues relating to it breaking too on the desktop.

**Comment by Poseidon444** [comment]
mov-cli breaking on 3.11 is due to the fact that lxml breaks in 3.11

**Comment by Poseidon444** [comment]
we'll have to wait till lxml has been fixed on 3.11 or use plain old html parser in bs4, but lxml has its advantages

**Comment by THEGOLDENPRO** [comment]
> we'll have to wait till lxml has been fixed on 3.11 or use plain old html parser in bs4, but lxml has its advantages

Yeah I guess we'll have to wait

**Comment by the-real-ale** [comment]
> i get an, lxml unable to compile error and i'm unable to install python 3.10 on termux. How do i install python 3.10 on termux?

What was the specific error? I got this branch set up on termux with python 3.11. I had to specifically install some xml packages with 'pkg install' but otherwise it was smooth sailing.

**Comment by THEGOLDENPRO** [comment]
> > i get an, lxml unable to compile error and i'm unable to install python 3.10 on termux. How do i install python 3.10 on termux?
> 
> What was the specific error? I got this branch set up on termux with python 3.11. I had to specifically install some xml packages with 'pkg install' but otherwise it was smooth sailing.

Yep, I can confirm. I tested it just now on Termux with python 3.11 and it works just like before when I tested it on 3.10.

**Comment by Poseidon444** [comment]
Ic, I'll try it out once

**Comment by ghost** [comment]
@THEGOLDENPRO Please fix the Conflicts and i will merge it as @the-real-ale and you confirmed it as working.

**Comment by THEGOLDENPRO** [comment]
> @THEGOLDENPRO Please fix the Conflicts and i will merge it as @the-real-ale and you confirmed it as working.

Alright 👍

**Comment by R3tr0Ananas** [comment]
> > @THEGOLDENPRO Please fix the Conflicts and i will merge it as @the-real-ale and you confirmed it as working.
> 
> Alright 👍

Well i just wanted to add fzf but with Android it isn't going to work or does it work with android?

**Comment by THEGOLDENPRO** [comment]
I will fix these merge conflicts now and then retest on my Pixel 4a 5G.

> *wish me luck 💀*

merge-conflict

**Comment by R3tr0Ananas** [comment]
So i take from the Commit Message that's fixed and tested

**Review by ghost — APPROVED** [review]
works

**Comment by THEGOLDENPRO** [comment]
> So i take from the Commit Message that's fixed and tested

Yep, I've tested the streaming capabilities but I wasn't able to completely test downloading on Android, although I did try it and ffmpeg was downloading something.

Apart from that everything else seems to work properly.

**Comment by ghost** [comment]
I guess thats okay

**Pull request merged**
