### PR TITLE
add a setable Download Loaction and a Discord Rich Presence that you can enable and disable

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Poseidon444** [comment]
Will look into

**Comment by ghost** [comment]
Note: you can´t click on the Button with the same account you will need another account or i can send screenshots

**Comment by ghost** [comment]
grafik

**Comment by Poseidon444** [comment]
image
The application becomes unusable without discord installed.

**Comment by ghost** [comment]
Should be fixed now

**Comment by Poseidon444** [comment]
I'll take a look

**Comment by ghost** [comment]
Fixed #46 That Python Version does work on macos.

The "No such file or directory" part

**Comment by Poseidon444** [comment]
I see

**Review by Poseidon444 — COMMENTED** [review]
Lsgtm

**Pull request merged**
