### PR TITLE
Fixed colours in windows 10 cmd terminal

### PR DESCRIPTION
**Pull request by THEGOLDENPRO**
## **Before**
image

## **After**
image

### CODE REVIEW

**Comment by Poseidon444** [comment]
Does it have any impact on other terminals(unix)?

**Comment by THEGOLDENPRO** [comment]
> Does it have any impact on other terminals(unix)?

I'll try it out on Ubuntu.

**Comment by Poseidon444** [comment]
Did it have any effects?

**Comment by THEGOLDENPRO** [comment]
> Did it have any effects?

Sorry for the long wait. It still works correctly on Ubuntu but as you might see on the first line you get ``sh: 1: color: not found``, so I guess I'll just need to add an os check for windows before running ``os.system('color FF')`` to get rid of that.
image

**Comment by Poseidon444** [comment]
Thanks a lot, this will be merged and the os check will be implemented in the next commit

**Pull request merged**
