### PR TITLE
gogoanime link

### PR DESCRIPTION
**Pull request by GDjkhp**
image

### CODE REVIEW

**Comment by 4cecoder** [comment]
Test time!

**Comment by Poseidon444** [comment]
It didnot work for me, but the updated url is the new url for gogo

**Comment by THEGOLDENPRO** [comment]
> Test time!

does it work?

**Comment by Poseidon444** [comment]
It did not work for me, idk why, it should quite obviously work

**Comment by THEGOLDENPRO** [comment]
> It did not work for me, idk why, it should quite obviously work

Try a VPN/change DNS. Maybe?

**Comment by GDjkhp** [comment]
> It did not work for me, idk why, it should quite obviously work

you have to delete that appdata file to reset

**Comment by 4cecoder** [comment]
It's likely that we need to work on a function to do lookups and update the (appdata)
file that stores the metadata every so often

**Comment by THEGOLDENPRO** [comment]
v3 codebase be like 😭

**Comment by Poseidon444** [comment]
> > It did not work for me, idk why, it should quite obviously work
> 
> you have to delete that appdata file to reset

I see, i'll try it out

**Comment by Poseidon444** [comment]
Works!!

**Pull request merged**
